<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <DebugType>Embedded</DebugType>
        <EmbedAllSources>True</EmbedAllSources>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BH.DIS.SDK" Version="2.2.12-rc.137"/>
        <PackageReference Include="Delegateas.DeveloperExperience" Version="0.1.0-alpha0177" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0"/>
    </ItemGroup>

</Project>
